export let users = [
    {id:1 , name: 'Temurbek1' },
    {id:2 , name: 'Temurbek2' },
    {id:3 , name: 'Temurbek3' },
    {id:4 , name: 'Temurbek4' },
    {id:5 , name: 'Temurbek5' },
    {id:6 , name: 'Temurbek6' },
    {id:7 , name: 'Temurbek7' },
    {id:8 , name: 'Temurbek8' },
    {id:9 , name: 'Temurbek1' },
    {id:10 , name: 'Temurbek2' },
    {id:11 , name: 'Temurbek3' },
    {id:12 , name: 'Temurbek4' },
    {id:13, name: 'Temurbek5' },
    {id:14, name: 'Temurbek6' },
    {id:15, name: 'Temurbek7' },
    {id:16, name: 'Temurbek8' }, 
    {id:17, name: 'Temurbek2' },
    {id:18, name: 'Temurbek3' },
    {id:19, name: 'Temurbek4' },
    {id:20, name: 'Temurbek5' },
    {id:21, name: 'Temurbek6' },
    {id:22, name: 'Temurbek7' },
    {id:23, name: 'Temurbek8' },
    {id:24, name: 'Temurbek1' },
    {id:25, name: 'Temurbek2' },
    {id:26, name: 'Temurbek3' },
    {id:27, name: 'Temurbek4' },
    {id:28, name: 'Temurbek5' },
    {id:29, name: 'Temurbek6' },
    {id:30, name: 'Temurbek7' },
    {id:31, name: 'Temurbek8' },
  
]

export const list = [1,2,3,4,5,6]